import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900">
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar */}
          <aside className="w-64 bg-slate-900 text-white flex flex-col">
            <div className="h-16 flex items-center px-6 font-bold text-lg border-b border-slate-800">
              Agentic Commerce
            </div>
            <nav className="flex-1 py-4 px-3 space-y-1">
              <a href="#" className="bg-indigo-600 text-white group flex items-center px-3 py-2 text-sm font-medium rounded-md">
                Dashboard
              </a>
              <a href="#" className="text-slate-300 hover:bg-slate-800 hover:text-white group flex items-center px-3 py-2 text-sm font-medium rounded-md">
                Orders
              </a>
              <a href="#" className="text-slate-300 hover:bg-slate-800 hover:text-white group flex items-center px-3 py-2 text-sm font-medium rounded-md">
                Products
              </a>
              <a href="#" className="text-slate-300 hover:bg-slate-800 hover:text-white group flex items-center px-3 py-2 text-sm font-medium rounded-md">
                Agent Rules
              </a>
            </nav>
            <div className="p-4 border-t border-slate-800 text-sm text-slate-400">
              <p>TechNova Gaming</p>
              <p className="text-xs mt-1">Status: Active</p>
            </div>
          </aside>

          {/* Main content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            <header className="h-16 bg-white border-b border-slate-200 flex items-center px-6 justify-between shrink-0">
              <h1 className="text-xl font-semibold text-slate-800">Merchant Dashboard</h1>
              <div className="flex items-center space-x-4">
                <span className="flex h-8 w-8 items-center justify-center rounded-full bg-indigo-100 text-indigo-700 font-medium">
                  TN
                </span>
              </div>
            </header>
            <main className="flex-1 overflow-y-auto p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
