"""Phase 6 Schema Updates

Revision ID: 12ecd24f424f
Revises: fd2c4842b154
Create Date: 2026-08-24 20:14:33.940472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ecd24f424f'
down_revision: Union[str, Sequence[str], None] = 'fd2c4842b154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('agent_decisions', sa.Column('scoring_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_decisions', 'scoring_details')
    op.drop_column('agent_decisions', 'score')
    # ### end Alembic commands ###
