"""Add agentic payment limits to Customer

Revision ID: 23203fac1554
Revises: 82f8c06b2b3c
Create Date: 2026-09-04 17:17:38.288041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23203fac1554'
down_revision: Union[str, Sequence[str], None] = '82f8c06b2b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('transaction_limit', sa.Numeric(), nullable=True))
    op.add_column('customers', sa.Column('daily_limit', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'daily_limit')
    op.drop_column('customers', 'transaction_limit')
    # ### end Alembic commands ###
