"""Add decision_type to agent_decisions

Revision ID: 39b83933fd91
Revises: 6ed9cfafdc5c
Create Date: 2026-08-31 10:50:08.295370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b83933fd91'
down_revision: Union[str, Sequence[str], None] = '6ed9cfafdc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('decision_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_decisions', 'decision_type')
    # ### end Alembic commands ###
