"""Add agentic payment authorization

Revision ID: 49b6d2e194ec
Revises: d096042c02f4
Create Date: 2026-08-29 11:12:46.851030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49b6d2e194ec'
down_revision: Union[str, Sequence[str], None] = 'd096042c02f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_table('agentic_payment_authorizations',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('rail', sa.String(), nullable=False),
    sa.Column('authorization_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('per_transaction_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spent_today', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentic_payment_authorizations_customer_id'), 'agentic_payment_authorizations', ['customer_id'], unique=False)
    op.create_table('user_spending_limits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_limit', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_spending_limits_user_id'), 'user_spending_limits', ['user_id'], unique=True)
    op.add_column('payments', sa.Column('agentic_authorization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_agentic_authorization_id'), 'payments', ['agentic_authorization_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'agentic_payment_authorizations', ['agentic_authorization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_agentic_authorization_id'), table_name='payments')
    op.drop_column('payments', 'agentic_authorization_id')
    op.drop_index(op.f('ix_user_spending_limits_user_id'), table_name='user_spending_limits')
    op.drop_table('user_spending_limits')
    op.drop_index(op.f('ix_agentic_payment_authorizations_customer_id'), table_name='agentic_payment_authorizations')
    op.drop_table('agentic_payment_authorizations')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
