"""Add multi-source and promotions

Revision ID: 5d7578d077d8
Revises: 6f81e3bc2de0
Create Date: 2026-08-26 11:05:39.247285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7578d077d8'
down_revision: Union[str, Sequence[str], None] = '6f81e3bc2de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_category', sa.String(), nullable=True),
    sa.Column('target_keywords', sa.String(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('agent_recommendations', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_merchant_id'), 'promotions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_promotions_product_id'), 'promotions', ['product_id'], unique=False)
    op.create_index(op.f('ix_promotions_status'), 'promotions', ['status'], unique=False)
    op.add_column('products', sa.Column('source', sa.String(), server_default='razorpay', nullable=False))
    op.add_column('products', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('delivery_estimate', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_sponsored', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('product_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_source'), 'products', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_source'), table_name='products')
    op.drop_column('products', 'product_url')
    op.drop_column('products', 'is_sponsored')
    op.drop_column('products', 'delivery_estimate')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'source')
    op.drop_index(op.f('ix_promotions_status'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_product_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_merchant_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
