"""Add merchant_id to agentic authorization

Revision ID: 6ed9cfafdc5c
Revises: ef445420d018
Create Date: 2026-08-29 12:34:24.196007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed9cfafdc5c'
down_revision: Union[str, Sequence[str], None] = 'ef445420d018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentic_payment_authorizations', sa.Column('merchant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_agentic_payment_authorizations_merchant_id'), 'agentic_payment_authorizations', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'agentic_payment_authorizations', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agentic_payment_authorizations', type_='foreignkey')
    op.drop_index(op.f('ix_agentic_payment_authorizations_merchant_id'), table_name='agentic_payment_authorizations')
    op.drop_column('agentic_payment_authorizations', 'merchant_id')
    # ### end Alembic commands ###
