"""phase_7_policy_and_consent

Revision ID: 6f81e3bc2de0
Revises: 12ecd24f424f
Create Date: 2026-08-24 20:43:55.369941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f81e3bc2de0'
down_revision: Union[str, Sequence[str], None] = '12ecd24f424f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_requests',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('policy_decision', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_requests_cart_id'), 'consent_requests', ['cart_id'], unique=False)
    op.create_index(op.f('ix_consent_requests_customer_id'), 'consent_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_consent_requests_merchant_id'), 'consent_requests', ['merchant_id'], unique=False)
    op.add_column('carts', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'discount')
    op.drop_index(op.f('ix_consent_requests_merchant_id'), table_name='consent_requests')
    op.drop_index(op.f('ix_consent_requests_customer_id'), table_name='consent_requests')
    op.drop_index(op.f('ix_consent_requests_cart_id'), table_name='consent_requests')
    op.drop_table('consent_requests')
    # ### end Alembic commands ###
