"""Add User and WebhookEvent

Revision ID: 76f7b423e7c2
Revises: 9eb2cc20ad2c
Create Date: 2026-08-26 11:46:24.544633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76f7b423e7c2'
down_revision: Union[str, Sequence[str], None] = '9eb2cc20ad2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_merchant_id'), 'users', ['merchant_id'], unique=False)
    op.add_column('webhook_events', sa.Column('event_id', sa.String(), nullable=False))
    op.add_column('webhook_events', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('webhook_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('webhook_events', sa.Column('signature_valid', sa.Boolean(), nullable=True))
    op.add_column('webhook_events', sa.Column('processing_error', sa.String(), nullable=True))
    op.add_column('webhook_events', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.drop_column('webhook_events', 'processed')
    op.add_column('webhook_events', sa.Column('processed', sa.Boolean(), nullable=True, default=False))
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.drop_column('webhook_events', 'provider')
    op.drop_column('webhook_events', 'provider_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('provider_event_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('webhook_events', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.alter_column('webhook_events', 'processed',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('webhook_events', 'processed_at')
    op.drop_column('webhook_events', 'processing_error')
    op.drop_column('webhook_events', 'signature_valid')
    op.drop_column('webhook_events', 'payload')
    op.drop_column('webhook_events', 'account_id')
    op.drop_column('webhook_events', 'event_id')
    op.drop_index(op.f('ix_users_merchant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
