"""Add webhook_verified to Payment

Revision ID: 82f8c06b2b3c
Revises: c428ab54da81
Create Date: 2026-09-04 11:02:53.060599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f8c06b2b3c'
down_revision: Union[str, Sequence[str], None] = 'c428ab54da81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('webhook_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'webhook_verified')
    # ### end Alembic commands ###
