"""add_image_url_and_mrp

Revision ID: 9eb2cc20ad2c
Revises: 5d7578d077d8
Create Date: 2026-08-26 11:19:07.281033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb2cc20ad2c'
down_revision: Union[str, Sequence[str], None] = '5d7578d077d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'mrp')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
