"""Add razorpay fields to User

Revision ID: c428ab54da81
Revises: 39b83933fd91
Create Date: 2026-09-03 20:10:54.981254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c428ab54da81'
down_revision: Union[str, Sequence[str], None] = '39b83933fd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'cart_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('active_mandate_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reserved_balance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reserved_balance')
    op.drop_column('users', 'active_mandate_token')
    op.drop_column('users', 'razorpay_customer_id')
    op.alter_column('orders', 'cart_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
