"""split product and offer

Revision ID: d096042c02f4
Revises: 76f7b423e7c2
Create Date: 2026-08-26 16:26:36.990479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd096042c02f4'
down_revision: Union[str, Sequence[str], None] = '76f7b423e7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('delivery_estimate', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_is_active'), 'offers', ['is_active'], unique=False)
    op.create_index(op.f('ix_offers_merchant_id'), 'offers', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_offers_product_id'), 'offers', ['product_id'], unique=False)
    op.add_column('cart_items', sa.Column('offer_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_offer_id'), 'cart_items', ['offer_id'], unique=False)
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'offers', ['offer_id'], ['id'])
    op.drop_column('cart_items', 'product_id')
    op.add_column('inventories', sa.Column('offer_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_inventories_product_id'), table_name='inventories')
    op.create_index(op.f('ix_inventories_offer_id'), 'inventories', ['offer_id'], unique=True)
    op.drop_constraint(op.f('inventories_product_id_fkey'), 'inventories', type_='foreignkey')
    op.create_foreign_key(None, 'inventories', 'offers', ['offer_id'], ['id'])
    op.drop_column('inventories', 'product_id')
    op.add_column('merchants', sa.Column('ai_commerce_enabled', sa.Boolean(), nullable=False))
    op.add_column('merchants', sa.Column('ai_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('merchants', sa.Column('agent_purchases_enabled', sa.Boolean(), nullable=False))
    op.add_column('order_items', sa.Column('offer_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_offer_id'), 'order_items', ['offer_id'], unique=False)
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'offers', ['offer_id'], ['id'])
    op.drop_column('order_items', 'product_id')
    op.alter_column('products', 'merchant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_source'), table_name='products')
    op.drop_column('products', 'delivery_estimate')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'source')
    op.drop_column('products', 'price')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'is_sponsored')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'mrp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('mrp', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('is_sponsored', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('source', sa.VARCHAR(), server_default=sa.text("'razorpay'::character varying"), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('delivery_estimate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_products_source'), 'products', ['source'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.alter_column('products', 'merchant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('order_items', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_offer_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_column('order_items', 'offer_id')
    op.drop_column('merchants', 'agent_purchases_enabled')
    op.drop_column('merchants', 'ai_discount_percent')
    op.drop_column('merchants', 'ai_commerce_enabled')
    op.add_column('inventories', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key(op.f('inventories_product_id_fkey'), 'inventories', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_inventories_offer_id'), table_name='inventories')
    op.create_index(op.f('ix_inventories_product_id'), 'inventories', ['product_id'], unique=True)
    op.drop_column('inventories', 'offer_id')
    op.add_column('cart_items', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_cart_items_offer_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.drop_column('cart_items', 'offer_id')
    op.drop_index(op.f('ix_offers_product_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_merchant_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_is_active'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
