"""Add policy and general logging fields to AgentDecision

Revision ID: ef445420d018
Revises: 49b6d2e194ec
Create Date: 2026-08-29 12:21:07.222075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef445420d018'
down_revision: Union[str, Sequence[str], None] = '49b6d2e194ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('action', sa.String(), nullable=True))
    op.add_column('agent_decisions', sa.Column('actor_type', sa.String(), nullable=True))
    op.add_column('agent_decisions', sa.Column('decision_status', sa.String(), nullable=True))
    op.add_column('agent_decisions', sa.Column('policy_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_decisions', 'policy_rules')
    op.drop_column('agent_decisions', 'decision_status')
    op.drop_column('agent_decisions', 'actor_type')
    op.drop_column('agent_decisions', 'action')
    # ### end Alembic commands ###
