"""add_source_to_order

Revision ID: fd2c4842b154
Revises: e5c223a557af
Create Date: 2026-08-24 15:43:25.952010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2c4842b154'
down_revision: Union[str, Sequence[str], None] = 'e5c223a557af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('source', sa.String(), server_default='DIRECT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'source')
    # ### end Alembic commands ###
